version: '3.4'
services:
  #PHP Service
  php:
    build:
      context: ./docker_files
      dockerfile: php.dockerfile
    image: dahaltn/php-fpm:8.1
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./web:/var/www
      - ./php/php-development.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./web:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    ports:
      - 80:80
      - 443:443

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: lara
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: P@ssword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/mysql.cnf:/etc/mysql/mysql.cnf
    networks:
      - app-network

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-network"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.routers.adminer.rule=Host(`adminer.app.local`)"
    environment:
      ADMINER_PLUGINS: 'tables-filter tinymce'
    networks:
      - app-network
    ports:
      - 8080:8080

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      -  app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
    external: false
#Volumes
volumes:
  dbdata:
    driver: local
